version: "3.8"
services:
  void:
    image: greghib/void
    volumes:
      - ./data/saves/:/app/data/saves
      - ./data/grand_exchange/:/app/data/grand_exchange
    environment:
      storage: database
      storage.database.username: postgres
      storage.database.password: password
      storage.database.driver: org.postgresql.Driver
      storage.database.jdbcUrl: jdbc:postgresql://db:5432/game?reWriteBatchedInserts=true
    ports:
      - "43594:43594"
    depends_on:
      - db
    networks:
      - internal_network
  db:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_DB: game
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - internal_network
networks:
  internal_network:
    driver: bridge